algoritmo "Divisão numérica"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n1, n2: Inteiro
m: Real

inicio

escreva("Informe um número: ")
leia(n1)
escreva("Informe outro número: ")
leia(n2)
m <- (n1 + n2)/2
escreva ("A média entre ", n1, " e ", n2, " é igual a ", m)

fimalgoritmo